on:
  workflow_dispatch:
    inputs:
      container_registry_url:
        description: 'The url of the container registry to publish to'
        type: string
        required: true

jobs:
  deploy:

    permissions:
      id-token: write
      contents: read
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Azure Login
        uses: Azure/login@v2.1.1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: |
          az acr login --name ${{ inputs.container_registry_url }}
      
      - name: Build Docker Image
        run: |
          IMAGE_NAME="${{ inputs.container_registry_url }}/dash:latest"
          docker build -t $IMAGE_NAME ./apps/dash

      - name: Push Docker image to ACR
        run: |
          IMAGE_NAME="${{ inputs.container_registry_url }}/tasky:latest"
          docker push $IMAGE_NAME